[2025-10-04T21:37:19.798+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: economic_data_daily_update.update_ism_manufacturing scheduled__2025-10-03T06:00:00+00:00 [queued]>
[2025-10-04T21:37:19.821+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: economic_data_daily_update.update_ism_manufacturing scheduled__2025-10-03T06:00:00+00:00 [queued]>
[2025-10-04T21:37:19.823+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-10-04T21:37:19.860+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): update_ism_manufacturing> on 2025-10-03 06:00:00+00:00
[2025-10-04T21:37:19.866+0000] {standard_task_runner.py:60} INFO - Started process 224 to run task
[2025-10-04T21:37:19.881+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'economic_data_daily_update', 'update_ism_manufacturing', 'scheduled__2025-10-03T06:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/economic_data_daily_update.py', '--cfg-path', '/tmp/tmpws0yhb49']
[2025-10-04T21:37:19.890+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask update_ism_manufacturing
[2025-10-04T21:37:20.017+0000] {task_command.py:423} INFO - Running <TaskInstance: economic_data_daily_update.update_ism_manufacturing scheduled__2025-10-03T06:00:00+00:00 [running]> on host c5589f85b7af
[2025-10-04T21:37:58.803+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='economic_data_team' AIRFLOW_CTX_DAG_ID='economic_data_daily_update' AIRFLOW_CTX_TASK_ID='update_ism_manufacturing' AIRFLOW_CTX_EXECUTION_DATE='2025-10-03T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-03T06:00:00+00:00'
[2025-10-04T21:37:58.856+0000] {logging_mixin.py:188} INFO - Updating ISM Manufacturing Index...
[2025-10-04T21:37:59.134+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/economic_data_daily_update.py", line 421, in update_ism_manufacturing
    log_update('survey_data', 'ism_manufacturing', 0, 'success')
  File "/opt/airflow/dags/utils/db_helpers.py", line 42, in log_update
    hook.run(sql, parameters=(schema, table, source_id, records_added, status, error_message))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 128, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `timescaledb_conn` isn't defined
[2025-10-04T21:37:59.321+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=economic_data_daily_update, task_id=update_ism_manufacturing, execution_date=20251003T060000, start_date=20251004T213719, end_date=20251004T213759
[2025-10-04T21:37:59.442+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task update_ism_manufacturing (The conn_id `timescaledb_conn` isn't defined; 224)
[2025-10-04T21:37:59.501+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-04T21:38:00.678+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
