[2025-10-04T21:38:04.570+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: economic_data_daily_update.update_usd_trade_weighted manual__2025-10-04T21:30:38.497094+00:00 [queued]>
[2025-10-04T21:38:04.581+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: economic_data_daily_update.update_usd_trade_weighted manual__2025-10-04T21:30:38.497094+00:00 [queued]>
[2025-10-04T21:38:04.587+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-10-04T21:38:04.599+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): update_usd_trade_weighted> on 2025-10-04 21:30:38.497094+00:00
[2025-10-04T21:38:04.607+0000] {standard_task_runner.py:60} INFO - Started process 306 to run task
[2025-10-04T21:38:04.611+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'economic_data_daily_update', 'update_usd_trade_weighted', 'manual__2025-10-04T21:30:38.497094+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/economic_data_daily_update.py', '--cfg-path', '/tmp/tmpx1_086bs']
[2025-10-04T21:38:04.614+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask update_usd_trade_weighted
[2025-10-04T21:38:04.686+0000] {task_command.py:423} INFO - Running <TaskInstance: economic_data_daily_update.update_usd_trade_weighted manual__2025-10-04T21:30:38.497094+00:00 [running]> on host c5589f85b7af
[2025-10-04T21:38:05.030+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='economic_data_team' AIRFLOW_CTX_DAG_ID='economic_data_daily_update' AIRFLOW_CTX_TASK_ID='update_usd_trade_weighted' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T21:30:38.497094+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-04T21:30:38.497094+00:00'
[2025-10-04T21:38:08.582+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/economic_data_daily_update.py", line 390, in update_usd_trade_weighted
    df = client.get_series(series_id, start_date='2020-01-01')
  File "/opt/airflow/dags/utils/api_clients.py", line 64, in get_series
    data = self._make_request('series/observations', params)
  File "/opt/airflow/dags/utils/api_clients.py", line 31, in _make_request
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.stlouisfed.org/fred/series/observations?series_id=DTWEXBGS&api_key=your_fred_api_key_here&file_type=json&observation_start=2020-01-01
[2025-10-04T21:38:08.592+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=economic_data_daily_update, task_id=update_usd_trade_weighted, execution_date=20251004T213038, start_date=20251004T213804, end_date=20251004T213808
[2025-10-04T21:38:08.601+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task update_usd_trade_weighted (400 Client Error: Bad Request for url: https://api.stlouisfed.org/fred/series/observations?series_id=DTWEXBGS&api_key=your_fred_api_key_here&file_type=json&observation_start=2020-01-01; 306)
[2025-10-04T21:38:08.639+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-04T21:38:08.676+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
